spring:
  application:
    name: sc_cnf_srv
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CrazyZfp/spring-cloud-demo
          search-paths: configs
          username:
          password:

      label: master