spring:
  application:
    name: sc_cnf_srv
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CrazyZfp/spring-cloud-demo-configs
          search-paths: .
          username:
          password:
          default-label: master
      label: master
  profiles:
    active: dev